################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_LMDB "lmdb")
    if (NOT PC_LMDB_FOUND)
        pkg_check_modules(PC_LMDB "lmdb")
    endif (NOT PC_LMDB_FOUND)
    if (PC_LMDB_FOUND)
        # add CFLAGS from pkg-config file, e.g. draft api.
        add_definitions(${PC_LMDB_CFLAGS} ${PC_LMDB_CFLAGS_OTHER})
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_LMDB_INCLUDE_HINTS ${PC_LMDB_INCLUDE_DIRS} ${PC_LMDB_INCLUDE_DIRS}/*)
        set(PC_LMDB_LIBRARY_HINTS ${PC_LMDB_LIBRARY_DIRS} ${PC_LMDB_LIBRARY_DIRS}/*)
    endif(PC_LMDB_FOUND)
endif (NOT MSVC)

find_path (
    LMDB_INCLUDE_DIRS
    NAMES lmdb.h
    HINTS ${PC_LMDB_INCLUDE_HINTS}
)

find_library (
    LMDB_LIBRARIES
    NAMES lmdb
    HINTS ${PC_LMDB_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    LMDB
    REQUIRED_VARS LMDB_LIBRARIES LMDB_INCLUDE_DIRS
)
mark_as_advanced(
    LMDB_FOUND
    LMDB_LIBRARIES LMDB_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
