/*  =========================================================================
    classlmdb - generated layer of public API

    Copyright (c) 2017 Inkblot Software Limited.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef CLASSLMDB_LIBRARY_H_INCLUDED
#define CLASSLMDB_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>
#include <lmdb.h>

//  CLASSLMDB version macros for compile-time API detection
#define CLASSLMDB_VERSION_MAJOR 0
#define CLASSLMDB_VERSION_MINOR 0
#define CLASSLMDB_VERSION_PATCH 0

#define CLASSLMDB_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define CLASSLMDB_VERSION \
    CLASSLMDB_MAKE_VERSION(CLASSLMDB_VERSION_MAJOR, CLASSLMDB_VERSION_MINOR, CLASSLMDB_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined CLASSLMDB_STATIC
#       define CLASSLMDB_EXPORT
#   elif defined CLASSLMDB_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define CLASSLMDB_EXPORT __declspec(dllexport)
#       else
#           define CLASSLMDB_EXPORT
#       endif
#   elif defined CLASSLMDB_EXPORTS
#       define CLASSLMDB_EXPORT __declspec(dllexport)
#   else
#       define CLASSLMDB_EXPORT __declspec(dllimport)
#   endif
#   define CLASSLMDB_PRIVATE
#else
#   define CLASSLMDB_EXPORT
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define CLASSLMDB_PRIVATE __attribute__ ((visibility ("hidden")))
#   else
#       define CLASSLMDB_PRIVATE
#   endif
#endif

//  Project has no stable classes, so we build the draft API
#undef  CLASSLMDB_BUILD_DRAFT_API
#define CLASSLMDB_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef CLASSLMDB_BUILD_DRAFT_API
typedef struct _lmdbenv_t lmdbenv_t;
#define LMDBENV_T_DEFINED
typedef struct _lmdbdbi_t lmdbdbi_t;
#define LMDBDBI_T_DEFINED
typedef struct _lmdbtxn_t lmdbtxn_t;
#define LMDBTXN_T_DEFINED
typedef struct _lmdbcur_t lmdbcur_t;
#define LMDBCUR_T_DEFINED
#endif // CLASSLMDB_BUILD_DRAFT_API


//  Public classes, each with its own header file
#include "classlmdb_lmdbspan.h"
#ifdef CLASSLMDB_BUILD_DRAFT_API
#include "lmdbenv.h"
#include "lmdbdbi.h"
#include "lmdbtxn.h"
#include "lmdbcur.h"
#endif // CLASSLMDB_BUILD_DRAFT_API

#ifdef CLASSLMDB_BUILD_DRAFT_API
//  Self test for private classes
CLASSLMDB_EXPORT void
    classlmdb_private_selftest (bool verbose);
#endif // CLASSLMDB_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
