/*  =========================================================================
    lmdbtxn - Manager for an LMDB transaction

    Copyright (c) 2017 Inkblot Software Limited.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.
    =========================================================================
*/

#ifndef LMDBTXN_H_INCLUDED
#define LMDBTXN_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT
//  @warning Please edit the model at "api/lmdbtxn.xml" to make changes.
//  @interface
//  This API is a draft, and may change without notice.
#ifdef CLASSLMDB_BUILD_DRAFT_API
//  *** Draft method, for development use, may change without warning ***
//  Open a new read-only transaction for the provided lmdbenv.
//  Aborts (ends) the transaction on dtr call.
//  Returns NULL ir error.
CLASSLMDB_EXPORT lmdbtxn_t *
    lmdbtxn_new_rdonly (lmdbenv_t *env);

//  *** Draft method, for development use, may change without warning ***
//  As new_rdonly, but opens a read-write transaction.
//  Aborts on dbr call if not already committed.
CLASSLMDB_EXPORT lmdbtxn_t *
    lmdbtxn_new_rdrw (lmdbenv_t *env);

//  *** Draft method, for development use, may change without warning ***
//  Destroy the lmdbtxn.
CLASSLMDB_EXPORT void
    lmdbtxn_destroy (lmdbtxn_t **self_p);

//  *** Draft method, for development use, may change without warning ***
//  Commit transaction. Only valid for rdrw lmdbtxn's.
//  Returns 0 on success, -1 on error.
CLASSLMDB_EXPORT int
    lmdbtxn_commit (lmdbtxn_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Is this a read-only transaction?
CLASSLMDB_EXPORT bool
    lmdbtxn_rdonly (lmdbtxn_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Return a pointer to the underlying MDB_txn.
//  BEWARE: this is an escape hatch for people that *really* need it; if you
//  need more functionality then prefer to extend this library to contain it.
CLASSLMDB_EXPORT MDB_txn *
    lmdbtxn_handle (lmdbtxn_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Self test of this class.
CLASSLMDB_EXPORT void
    lmdbtxn_test (bool verbose);

#endif // CLASSLMDB_BUILD_DRAFT_API
//  @end

#ifdef __cplusplus
}
#endif

#endif
