/*  =========================================================================
    lmdbenv - Manager for an LMDB Environment, the in-memory interface to an LMDB file on disk

    Copyright (c) 2017 Inkblot Software Limited.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.
    =========================================================================
*/

#ifndef LMDBENV_H_INCLUDED
#define LMDBENV_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT
//  @warning Please edit the model at "api/lmdbenv.xml" to make changes.
//  @interface
//  This API is a draft, and may change without notice.
#ifdef CLASSLMDB_BUILD_DRAFT_API
//  *** Draft method, for development use, may change without warning ***
//  Ctr. Accesses the LMDB file at the given path, creates if not present.
//  Assumes default limits of max file size = 1GB and max number of named
//  DBs in the file = 10.
//  Returns NULL on error.
CLASSLMDB_EXPORT lmdbenv_t *
    lmdbenv_new (const char *path);

//  *** Draft method, for development use, may change without warning ***
//  As simple constructor, but lets you control the max filesize and max
//  named DB count limits.
//  Note that we round max_size up to the nearest multiple of 4096.
CLASSLMDB_EXPORT lmdbenv_t *
    lmdbenv_new_withlimits (const char *path, size_t max_size, size_t max_dbs);

//  *** Draft method, for development use, may change without warning ***
//  Destroy the lmdbenv.
CLASSLMDB_EXPORT void
    lmdbenv_destroy (lmdbenv_t **self_p);

//  *** Draft method, for development use, may change without warning ***
//  Return a pointer to the underlying MDB_env instance.
//  BEWARE: this is an escape hatch for people that *really* need it; if you
//  need more functionality then prefer to extend this library to contain it.
CLASSLMDB_EXPORT MDB_env *
    lmdbenv_handle (lmdbenv_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Self test of this class.
CLASSLMDB_EXPORT void
    lmdbenv_test (bool verbose);

#endif // CLASSLMDB_BUILD_DRAFT_API
//  @end

#ifdef __cplusplus
}
#endif

#endif
